### ISSUE TITLE
Incorrect number of dimensions

### ISSUE THREAD

**Issue by ankushs0128** [ZJUFanLab/scCATCH_performance_comparison#3]
I´m receiving an error after  evidence-based scoring and annotation 
```
clu_ann <- scCATCH(clu_markers,
+                    species = 'Human',
+                    cancer = NULL,
+                    tissue =  c('Embryoid body','Brain','Embryo'))
```
Note: there are 1376 potential marker genes in CellMatch database for Human on Embryoid body, Brain, Embryo! 
Note: there are 60 cell types in CellMatch database for Human on Embryoid body, Brain, Embryo! 

Beginning evidence-based scoring and annotation 
**Error in object[object$cluster == clu.num[i], ] : 
  incorrect number of dimensions**

**Comment by ZJUFanLab** [comment]
Hello, you should use scCATCH like this
```
clu_ann <- scCATCH(clu_markers$clu_markers,
+                    species = 'Human',
+                    cancer = NULL,
+                    tissue =  c('Embryoid body','Brain','Embryo'))
```
