### ISSUE TITLE
Accessing datasets

### ISSUE THREAD

**Issue by j-bac** [ZJUFanLab/scCATCH_performance_comparison#4]
Many thanks for your study and the scCATCH tool ! Would you have the benchmark datasets with annotations, to share with a link ? They are not always easily available from the studies or accession number, that would be really useful

**Comment by multitalk** [comment]
Hello, you can refer to the recently published benchmark datasets, namely mouse cell atlas [(MCA)](https://pubmed.ncbi.nlm.nih.gov/29474909) and human cell landscape [(HCL)](https://pubmed.ncbi.nlm.nih.gov/32214235) by Guo's group.
