### ISSUE TITLE
typo(?) in CellMatch table

### ISSUE THREAD

**Issue by victorkim0527** [ZJUFanLab/scCATCH_performance_comparison#5]
Hello, thank you for useful analysis tool and detailed examples.
I found there are 343 cases of cellType column in CellMatch dataset you provided are written: 'Nornal cell' that looks like typo.
I wanted to be confirmed that they are just mistakes and can be replaced as 'Normal cell'

**Comment by multitalk** [comment]
Thanks for your careful review. It is 'Normal cell' and I have revised the mistake.
